application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5440
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "newsletter@localhost.com"
  authorization_token: "1234567890"
  timeout_milliseconds: 10000