name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image 
        image: postgres:14
        # Environment variables scoped only for the `postgres` element
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        # When you map ports using the ports keyword, GitHub uses the --publish command to publish the container’s ports to the Docker host
        # Opens tcp port 5432 on the host and service container
        ports:
          - 5440:5432
    steps:
    - uses: actions/checkout@v3
    
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Install postgresql-client
      run: sudo apt-get update && sudo apt-get install postgresql-client -y
    - name: Migrate database
      run: SKIP_DOCKER=true ./scripts/init_db.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
